#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:10:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# make output directory
mkdir -p out_dir

# run the actual python code
singularity exec docker://brainlife/mne:0.22.0 python3 main.py

#parse config.json for input parameters (here, we are pulling "fif")
#fif=$(jq -r .fif config.json)
#pip install mne
#python main.py


#store PSD plot on product.json
cat << EOF > product.json
{
    "brainlife": [
        { 
            "type": "image/png", 
	        "name": "FIF (raw data, 5s-segment)",
            "base64": "$(base64 -w 0 out_dir/1_channels.png)"
        },
        { 
            "type": "image/png", 
	        "name": "PSD (raw data)",
            "base64": "$(base64 -w 0 out_dir/2_psd.png)"
        },
        { 
            "type": "image/png", 
	        "name": "ICA",
            "base64": "$(base64 -w 0 out_dir/3_ica.png)"
        },
    ]
}
EOF

echo done!	