#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00

#parse config.json for input parameters (here, we are pulling "fif")

fif=$(jq -r .fif config.json)

pip install mne

python ./main.py $fif
