#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:10:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Guiomar Niso

# make output directory
mkdir -p out_dir

# run the actual python code
# singularity exec docker://brainlife/mne:0.22.0 python3 main.py

#parse config.json for input parameters (here, we are pulling "fif")
#python main.py
singularity exec docker://brainlife/mne:0.23dev python3 main.py


